export const APP_VERSION = '2026.06.29';

export const SUBJECTS = [
  { id: 'english', name: '英语', exam: '成人高考专升本公共课', daily: true },
  { id: 'politics', name: '政治', exam: '成人高考专升本公共课', daily: false },
  { id: 'math2', name: '高数（二）', exam: '经管类专业基础课', daily: false },
  { id: 'degree', name: '学位与论文', exam: '入学后拿学位证关键项', daily: false },
  { id: 'admin', name: '行政管理', exam: '入学后专业课方向', daily: false },
];

export const PLAN_MILESTONES = [
  {
    date: '2026-06-29',
    title: '启动期',
    detail: '确定上海师范大学成考专升本行政管理为主方案，建立每日学习节奏。',
  },
  {
    date: '2026-07-01',
    title: '基础期',
    detail: '英语每天学，政治和高数（二）轮换，先把常考基础点铺开。',
  },
  {
    date: '2026-08-15',
    title: '强化期',
    detail: '开始整章刷题和错题复盘，每周一次小测。',
  },
  {
    date: '2026-09-01',
    title: '报名窗口提醒',
    detail: '2026年上海成考报名时间以“上海招考热线”公告为准，参考2025年为9月上旬。',
  },
  {
    date: '2026-10-01',
    title: '冲刺期',
    detail: '每周至少一套模拟，政治背诵、英语作文模板、高数公式回炉。',
  },
  {
    date: '2026-10-24',
    title: '预计考试周',
    detail: '成人高考通常在10月下旬举行，具体日期等官方准考证确认。',
  },
  {
    date: '2027-03-01',
    title: '预计入学',
    detail: '录取后完成注册、缴费、学籍核验，开始2.5年学制学习。',
  },
  {
    date: '2029-01-01',
    title: '毕业与学位准备',
    detail: '盯紧课程平均分、论文查重与答辩、学位外语或等效英语条件。',
  },
];

export const KNOWLEDGE_CARDS = [
  {
    id: 'official-channel',
    subject: '报名',
    title: '只认官方入口',
    body: '报名以“上海招考热线”和上海师范大学继续教育学院官方通知为准。任何承诺包录取、包学位、免考试的机构都按高风险处理。',
    points: ['上海招考热线查报名公告', '上海师大继续教育学院查招生简章', '缴费在官方系统完成'],
  },
  {
    id: 'degree-risk',
    subject: '学位与论文',
    title: '学位证的真正难点',
    body: '毕业证主要看录取、学籍、课程和毕业流程。学位证还要看平均分、论文、查重、答辩和英语条件，不能只盯入学考试。',
    points: ['课程平均分尽量70分以上', '论文查重预留修改时间', '英语条件越早准备越稳'],
  },
  {
    id: 'english-daily-method',
    subject: '英语',
    title: '英语每天不断线',
    body: '英语最适合碎片化积累，也是学位条件里最容易被拖到最后的风险项。每天保底25分钟，词汇、语法、阅读、作文轮换。',
    points: ['10分钟词汇', '10分钟阅读或语法', '5分钟作文句型'],
  },
  {
    id: 'politics-method',
    subject: '政治',
    title: '政治靠框架和关键词',
    body: '政治不要从第一天死背整本书，先搭框架，再用选择题反推高频概念，考前集中背主观题关键词。',
    points: ['马原重理解', '毛中特重线索', '思修法基重关键词'],
  },
  {
    id: 'math-method',
    subject: '高数（二）',
    title: '高数（二）先保基础分',
    body: '经管类高数（二）优先拿函数、极限、导数、积分、概率基础题。不要一开始追难题，先把公式和题型变成熟练动作。',
    points: ['公式卡片每天看', '错题按题型归类', '每周做一次限时小卷'],
  },
  {
    id: 'admin-degree',
    subject: '行政管理',
    title: '行政管理入学后策略',
    body: '行政管理通常比理工、医学、艺术类更适合稳妥拿证。入学后重点是平时作业、线上学习、期末考试和论文节奏。',
    points: ['作业不要拖到截止日', '期末前两周复习重点', '论文题目选择资料多的方向'],
  },
];

export const REVIEW_POINTS = {
  english: [
    '每天背词要复现，不只看一遍。',
    '阅读先抓主题句，再看选项陷阱。',
    '作文准备通用开头、转折、结尾句。',
    '学位英语或等效条件要提前确认当年学校规则。',
  ],
  politics: [
    '马原：物质与意识、矛盾、实践与认识。',
    '毛中特：中国式现代化、新发展理念、依法治国。',
    '思修法基：理想信念、社会主义核心价值观、宪法法律基础。',
    '时政：考前2个月集中补。',
  ],
  math2: [
    '函数定义域和值域先看清。',
    '极限、连续、导数是一条线。',
    '积分题优先掌握基本公式和换元。',
    '概率题先分清独立、互斥、条件概率。',
  ],
  degree: [
    '课程平均分尽量从第一学期就控制在70分以上。',
    '论文选题要避开资料少、口径太大的题。',
    '查重、格式、答辩材料都要提前留缓冲。',
  ],
};

export const LESSON_LIBRARY = [
  {
    id: 'eng-lesson-001',
    taskIds: ['english-daily'],
    subject: '英语',
    title: '高频词 benefit 与基础句型',
    minutes: 25,
    sourceNote: '原创学习笔记；依据成人高考专升本英语常见词汇、语法和阅读题型整理，仅供个人备考学习。',
    objectives: ['掌握 benefit 的常见含义', '区分 since 与 for', '完成2道随堂题'],
    sections: [
      {
        heading: '核心词汇',
        body: 'benefit 作名词时常表示“好处、益处”，作动词时表示“使受益、得益于”。阅读题中常用 advantage、gain、help 等近义表达替换。',
        bullets: ['benefit from：从……中受益', 'be beneficial to：对……有益', 'public benefit：公共利益'],
      },
      {
        heading: '今日语法',
        body: '现在完成时常和 since、for 连用。since 后接时间点，for 后接时间段。',
        bullets: ['since 2020', 'for three years', 'has lived / have studied'],
      },
    ],
    examples: [
      {
        prompt: 'She has worked in Shanghai since 2020.',
        explanation: '2020 是时间点，所以用 since。句子表示动作从过去延续到现在。',
      },
    ],
    flashcards: [
      { front: 'benefit', back: '好处；使受益' },
      { front: 'since + 时间点', back: '从某个时间点以来' },
      { front: 'for + 时间段', back: '持续多长时间' },
    ],
    questions: [
      {
        id: 'lesson-eng-001-q1',
        subject: '英语',
        prompt: 'The word “benefit” is closest in meaning to which option?',
        options: ['advantage', 'problem', 'method', 'weather'],
        answer: 0,
        explanation: 'benefit 常表示“益处、好处”，最接近 advantage。',
        tags: ['lesson', 'vocabulary'],
      },
      {
        id: 'lesson-eng-001-q2',
        subject: '英语',
        prompt: 'She has studied English ___ two years.',
        options: ['since', 'for', 'at', 'on'],
        answer: 1,
        explanation: 'two years 是时间段，所以用 for。',
        tags: ['lesson', 'grammar'],
      },
    ],
  },
  {
    id: 'eng-lesson-002',
    taskIds: ['english-daily'],
    subject: '英语',
    title: '阅读主旨题与作文结尾句',
    minutes: 25,
    sourceNote: '原创学习笔记；依据成人高考英语阅读和写作常见题型整理。',
    objectives: ['识别主旨题关键词', '记住一个作文结尾句', '完成2道随堂题'],
    sections: [
      {
        heading: '阅读主旨题',
        body: '主旨题通常问 main idea、best title、mainly about。先看首段、尾段、每段首句和反复出现的关键词。',
        bullets: ['不要被细节句带跑', '标题要覆盖全文，不要只覆盖一段', '选项太绝对时要谨慎'],
      },
      {
        heading: '作文结尾',
        body: '成考作文不追求花哨，清楚表达态度最重要。可以准备通用句：In my opinion, taking action now is necessary.',
        bullets: ['观点清楚', '语法稳定', '可替换 taking action now'],
      },
    ],
    examples: [
      {
        prompt: 'The passage mainly talks about the importance of daily learning.',
        explanation: '看到 mainly talks about，先找文章反复出现的核心词 daily learning，而不是某一个例子。',
      },
    ],
    flashcards: [
      { front: 'main idea', back: '文章主旨' },
      { front: 'best title', back: '最佳标题' },
      { front: 'In my opinion...', back: '在我看来……' },
    ],
    questions: [
      {
        id: 'lesson-eng-002-q1',
        subject: '英语',
        prompt: 'A main idea question should be answered by focusing on:',
        options: ['topic sentence and repeated keywords', 'only the longest word', 'only numbers', 'only the last option'],
        answer: 0,
        explanation: '主旨题优先看主题句和反复出现的关键词。',
        tags: ['lesson', 'reading'],
      },
      {
        id: 'lesson-eng-002-q2',
        subject: '英语',
        prompt: 'Which sentence is suitable for a simple composition conclusion?',
        options: ['In my opinion, taking action now is necessary.', 'Yesterday I eat.', 'Because under table.', 'Very good very good.'],
        answer: 0,
        explanation: 'A 句结构完整，适合作为基础作文结尾句。',
        tags: ['lesson', 'writing'],
      },
    ],
  },
  {
    id: 'pol-lesson-001',
    taskIds: ['politics-core'],
    subject: '政治',
    title: '马原：物质与意识',
    minutes: 35,
    sourceNote: '原创学习笔记；依据成人高考专升本政治常考框架整理。',
    objectives: ['理解世界统一于物质', '掌握意识的能动作用', '完成2道随堂题'],
    sections: [
      {
        heading: '核心观点',
        body: '辩证唯物主义认为世界统一于物质，物质决定意识，意识对物质具有能动的反作用。',
        bullets: ['物质第一性', '意识第二性', '尊重客观规律和发挥主观能动性相统一'],
      },
      {
        heading: '答题句式',
        body: '遇到材料题时，可按“原理 + 材料 + 方法论”展开：物质决定意识，所以要从实际出发；意识具有能动作用，所以要树立正确认识并指导实践。',
        bullets: ['先写原理', '再扣材料', '最后写方法论'],
      },
    ],
    examples: [
      {
        prompt: '某地根据当地资源发展产业，体现什么方法论？',
        explanation: '体现一切从实际出发，尊重客观规律。',
      },
    ],
    flashcards: [
      { front: '物质和意识谁第一性？', back: '物质第一性，意识第二性。' },
      { front: '意识能动作用', back: '意识能认识世界并指导实践改造世界。' },
    ],
    questions: [
      {
        id: 'lesson-pol-001-q1',
        subject: '政治',
        prompt: '辩证唯物主义认为世界的本原是？',
        options: ['物质', '意识', '感觉', '理念'],
        answer: 0,
        explanation: '辩证唯物主义认为世界统一于物质。',
        tags: ['lesson', '马原'],
      },
      {
        id: 'lesson-pol-001-q2',
        subject: '政治',
        prompt: '“从实际出发”主要体现了哪一原理？',
        options: ['物质决定意识', '意识决定物质', '否认规律', '只看主观愿望'],
        answer: 0,
        explanation: '从实际出发体现物质决定意识、主观符合客观。',
        tags: ['lesson', '马原'],
      },
    ],
  },
  {
    id: 'pol-lesson-002',
    taskIds: ['politics-core'],
    subject: '政治',
    title: '新发展理念',
    minutes: 35,
    sourceNote: '原创学习笔记；依据政治公共课常考关键词整理。',
    objectives: ['背熟五大发展理念', '会用关键词判断选择题', '完成2道随堂题'],
    sections: [
      {
        heading: '五个关键词',
        body: '新发展理念包括创新、协调、绿色、开放、共享。选择题常考完整表述、排序和内涵匹配。',
        bullets: ['创新：第一动力', '协调：内生特点', '绿色：普遍形态', '开放：必由之路', '共享：根本目的'],
      },
    ],
    examples: [
      {
        prompt: '推进公共服务均等化，最贴近哪一发展理念？',
        explanation: '公共服务均等化强调发展成果更多更公平惠及人民，贴近共享。',
      },
    ],
    flashcards: [
      { front: '新发展理念五词', back: '创新、协调、绿色、开放、共享。' },
      { front: '共享发展', back: '发展成果由人民共享。' },
    ],
    questions: [
      {
        id: 'lesson-pol-002-q1',
        subject: '政治',
        prompt: '新发展理念包括创新、协调、绿色、开放和？',
        options: ['共享', '封闭', '保守', '分散'],
        answer: 0,
        explanation: '新发展理念是创新、协调、绿色、开放、共享。',
        tags: ['lesson', '毛中特'],
      },
      {
        id: 'lesson-pol-002-q2',
        subject: '政治',
        prompt: '发展成果更多更公平惠及全体人民，体现的是？',
        options: ['共享发展', '封闭发展', '片面发展', '停滞发展'],
        answer: 0,
        explanation: '共享强调人民共享发展成果。',
        tags: ['lesson', '毛中特'],
      },
    ],
  },
  {
    id: 'math2-lesson-001',
    taskIds: ['math2-core'],
    subject: '高数（二）',
    title: '函数定义域与基本极限',
    minutes: 35,
    sourceNote: '原创学习笔记；高教社公开目录显示高数（二）包含“极限和连续”等章节，本课按该常考范围整理。',
    objectives: ['会看分母和根号限制', '记住一个重要极限', '完成2道随堂题'],
    sections: [
      {
        heading: '定义域先看限制',
        body: '函数题先找不能取的 x：分母不能为0，偶次根号内不能小于0，对数真数要大于0。',
        bullets: ['分母：不等于0', '偶次根号：大于等于0', '对数：大于0'],
      },
      {
        heading: '重要极限',
        body: 'lim(x->0) sin x / x = 1。它是极限题的基础公式，看到 sin x 与 x 同阶时优先想到它。',
        bullets: ['x趋近0', 'sin x / x', '结果为1'],
      },
    ],
    examples: [
      {
        prompt: 'y = 1 / (x - 2) 的定义域',
        explanation: '分母 x - 2 不能为0，所以 x 不等于2。',
      },
    ],
    flashcards: [
      { front: '分母限制', back: '分母不能为0。' },
      { front: 'lim sin x / x', back: 'x->0 时等于1。' },
    ],
    questions: [
      {
        id: 'lesson-math2-001-q1',
        subject: '高数（二）',
        prompt: '函数 y = 1 / (x - 2) 的定义域是？',
        options: ['x 不等于 2', '全体实数', 'x 等于 2', 'x 小于 0'],
        answer: 0,
        explanation: '分母不能为0，所以 x - 2 不等于0。',
        tags: ['lesson', '函数'],
      },
      {
        id: 'lesson-math2-001-q2',
        subject: '高数（二）',
        prompt: 'lim(x->0) sin x / x 的值是？',
        options: ['1', '0', '无穷大', '-1'],
        answer: 0,
        explanation: '这是重要基本极限，值为1。',
        tags: ['lesson', '极限'],
      },
    ],
  },
  {
    id: 'math2-lesson-002',
    taskIds: ['math2-core'],
    subject: '高数（二）',
    title: '导数公式与单调性',
    minutes: 35,
    sourceNote: '原创学习笔记；高数（二）常考一元函数微分学，本课整理基础得分点。',
    objectives: ['掌握 x^n 求导', '用导数判断单调性', '完成2道随堂题'],
    sections: [
      {
        heading: '幂函数求导',
        body: '最常用公式：(x^n)\' = n x^(n-1)。例如 x^2 的导数是 2x，x^3 的导数是 3x^2。',
        bullets: ['先把指数放到前面', '指数减1', '常数项导数为0'],
      },
      {
        heading: '导数与单调性',
        body: '在某区间内 f\'(x) > 0，函数递增；f\'(x) < 0，函数递减。',
        bullets: ['正增负减', '先求导再判断符号', '注意题目给定区间'],
      },
    ],
    examples: [
      {
        prompt: 'f(x)=x^2，求 f\'(x)',
        explanation: '套公式：(x^2)\'=2x。',
      },
    ],
    flashcards: [
      { front: '(x^n)\'', back: 'n x^(n-1)' },
      { front: 'f\'(x)>0', back: '函数递增。' },
    ],
    questions: [
      {
        id: 'lesson-math2-002-q1',
        subject: '高数（二）',
        prompt: '若 y = x^2，则 y 的导数是？',
        options: ['2x', 'x', 'x^3', '2'],
        answer: 0,
        explanation: '幂函数求导公式：(x^n)\' = n x^(n-1)。',
        tags: ['lesson', '导数'],
      },
      {
        id: 'lesson-math2-002-q2',
        subject: '高数（二）',
        prompt: '若 f\'(x)>0 在区间内恒成立，则 f(x) 在该区间？',
        options: ['单调递增', '单调递减', '恒为0', '没有定义'],
        answer: 0,
        explanation: '导数大于0表示函数在该区间单调递增。',
        tags: ['lesson', '导数应用'],
      },
    ],
  },
  {
    id: 'review-lesson-001',
    taskIds: ['wrong-review'],
    subject: '复习',
    title: '错题复盘四步法',
    minutes: 20,
    sourceNote: '原创学习方法卡片。',
    objectives: ['定位错因', '写出识别点', '安排二刷'],
    sections: [
      {
        heading: '四步法',
        body: '错题不是看一眼答案就结束。按“错因、正确知识点、下次识别点、二刷日期”处理，才能减少重复错误。',
        bullets: ['错因：概念不清/审题失误/计算错误', '识别点：题目里哪个词提醒你用哪个知识', '二刷：间隔1-3天再做'],
      },
    ],
    examples: [{ prompt: '把“选错 because/because of”归类', explanation: '这是语法搭配错误，下次看到名词短语先想 because of。' }],
    flashcards: [{ front: '错题四步', back: '错因、知识点、识别点、二刷日期。' }],
    questions: [
      {
        id: 'lesson-review-001-q1',
        subject: '复习',
        prompt: '错题复盘最应该记录什么？',
        options: ['错因和下次识别点', '只记录分数', '只看正确答案', '直接删除'],
        answer: 0,
        explanation: '记录错因和识别点，才能避免重复犯错。',
        tags: ['lesson', 'review'],
      },
    ],
  },
  {
    id: 'exam-lesson-001',
    taskIds: ['weekly-exam', 'monthly-exam'],
    subject: '考试',
    title: '限时小测策略',
    minutes: 45,
    sourceNote: '原创应试策略卡片。',
    objectives: ['先限时再订正', '按科目统计薄弱点', '把错题回流到错题本'],
    sections: [
      {
        heading: '做卷顺序',
        body: '周考和月考不要边做边翻答案。先限时完成，再集中订正，最后把错误分为知识不会、审题错误、时间不够三类。',
        bullets: ['先计时', '再判分', '最后归因'],
      },
    ],
    examples: [{ prompt: '高数小卷错了3题，如何处理？', explanation: '先看是否同属导数/极限，再回到对应课程复习。' }],
    flashcards: [{ front: '模拟考三步', back: '限时、判分、归因。' }],
    questions: [
      {
        id: 'lesson-exam-001-q1',
        subject: '考试',
        prompt: '周考最稳妥的流程是？',
        options: ['先限时做题，再订正归因', '边看答案边做', '只看分数', '跳过错题'],
        answer: 0,
        explanation: '先限时才能测试真实状态，订正归因才能改进。',
        tags: ['lesson', 'exam'],
      },
    ],
  },
  {
    id: 'degree-lesson-001',
    taskIds: ['degree-english'],
    subject: '学位与论文',
    title: '入学后学位证风险控制',
    minutes: 30,
    sourceNote: '原创拿证策略笔记；依据上海师范大学继续教育学院公开学位规则整理。',
    objectives: ['明确平均分风险', '提前准备英语条件', '论文预留查重修改时间'],
    sections: [
      {
        heading: '三条主线',
        body: '毕业证看学籍、课程、作业、考试和毕业流程；学位证还要看平均分、外语条件、论文评审/答辩。入学后每门课目标不要只定及格。',
        bullets: ['课程平均分尽量75+', '英语条件越早越稳', '论文题目选资料充足方向'],
      },
    ],
    examples: [{ prompt: '某门课程只考61分怎么办？', explanation: '要立刻关注平均分是否受影响，后续课程用高分拉回。' }],
    flashcards: [{ front: '学位证三风险', back: '平均分、外语、论文。' }],
    questions: [
      {
        id: 'lesson-degree-001-q1',
        subject: '学位与论文',
        prompt: '入学后想稳妥拿学位，课程分数目标应怎样设？',
        options: ['尽量75分以上', '只要60分', '不看成绩', '只看论文'],
        answer: 0,
        explanation: '学位申请通常涉及平均分，目标留余量更稳妥。',
        tags: ['lesson', 'degree'],
      },
    ],
  },
  {
    id: 'admin-lesson-001',
    taskIds: ['course-work'],
    subject: '行政管理',
    title: '行政管理论述题答题骨架',
    minutes: 30,
    sourceNote: '原创专业学习方法卡片。',
    objectives: ['掌握概念-原因-措施结构', '为论文选题做准备'],
    sections: [
      {
        heading: '三段式骨架',
        body: '行政管理类题目常用“是什么、为什么、怎么办”展开。先界定概念，再分析原因或意义，最后给出措施。',
        bullets: ['是什么：定义和特征', '为什么：背景、意义、问题', '怎么办：主体、制度、流程、评价'],
      },
    ],
    examples: [{ prompt: '如何分析社区治理数字化？', explanation: '先解释数字化治理，再写提升效率和服务能力，最后写平台、数据、人员和监督措施。' }],
    flashcards: [{ front: '管理类论述结构', back: '概念 + 原因/意义 + 措施。' }],
    questions: [
      {
        id: 'lesson-admin-001-q1',
        subject: '行政管理',
        prompt: '行政管理论述题最常用的展开结构是？',
        options: ['概念、原因、措施', '只写结论', '只写个人感受', '只列数字'],
        answer: 0,
        explanation: '概念、原因、措施能让答案结构完整。',
        tags: ['lesson', 'admin'],
      },
    ],
  },
];

export const QUESTION_BANK = [
  {
    id: 'eng-001',
    subject: '英语',
    prompt: 'The word “benefit” is closest in meaning to which option?',
    options: ['advantage', 'problem', 'method', 'result'],
    answer: 0,
    explanation: 'benefit 常表示“好处、益处”，最接近 advantage。',
    tags: ['vocabulary'],
  },
  {
    id: 'eng-002',
    subject: '英语',
    prompt: 'Choose the best answer: She has lived in Shanghai ___ 2020.',
    options: ['for', 'since', 'at', 'during'],
    answer: 1,
    explanation: 'since 后接时间点，2020是时间点。',
    tags: ['grammar'],
  },
  {
    id: 'eng-003',
    subject: '英语',
    prompt: 'Choose the best answer: If I ___ enough time, I would review the notes again.',
    options: ['have', 'had', 'will have', 'am having'],
    answer: 1,
    explanation: '虚拟条件句中，与现在事实相反时 if 从句用过去式。',
    tags: ['grammar'],
  },
  {
    id: 'eng-004',
    subject: '英语',
    prompt: 'Which sentence is suitable for an exam composition conclusion?',
    options: [
      'In my opinion, taking action now is necessary.',
      'Yesterday I eat breakfast.',
      'The table is under because.',
      'Very good very nice.',
    ],
    answer: 0,
    explanation: 'A句表达完整，适合作文结尾观点句。',
    tags: ['writing'],
  },
  {
    id: 'eng-005',
    subject: '英语',
    prompt: 'Choose the best answer: The meeting was put off ___ the heavy rain.',
    options: ['because', 'because of', 'so', 'although'],
    answer: 1,
    explanation: 'because of 后接名词短语，the heavy rain 是名词短语。',
    tags: ['grammar'],
  },
  {
    id: 'eng-006',
    subject: '英语',
    prompt: 'Reading skill: When a passage asks for the “main idea”, what should you look for first?',
    options: ['Topic sentence and repeated keywords', 'Only the longest word', 'The last option', 'Numbers only'],
    answer: 0,
    explanation: '主旨题优先找主题句和反复出现的关键词。',
    tags: ['reading'],
  },
  {
    id: 'pol-001',
    subject: '政治',
    prompt: '马克思主义哲学认为，世界的本原是？',
    options: ['物质', '意识', '理念', '感觉'],
    answer: 0,
    explanation: '辩证唯物主义认为世界统一于物质。',
    tags: ['马原'],
  },
  {
    id: 'pol-002',
    subject: '政治',
    prompt: '实践在认识中的地位是？',
    options: ['认识的来源和检验标准', '与认识无关', '只影响情绪', '只适合自然科学'],
    answer: 0,
    explanation: '实践是认识的来源、动力、目的和检验真理的标准。',
    tags: ['马原'],
  },
  {
    id: 'pol-003',
    subject: '政治',
    prompt: '新发展理念包括创新、协调、绿色、开放和？',
    options: ['共享', '封闭', '保守', '分散'],
    answer: 0,
    explanation: '新发展理念是创新、协调、绿色、开放、共享。',
    tags: ['毛中特'],
  },
  {
    id: 'pol-004',
    subject: '政治',
    prompt: '全面依法治国的总目标是？',
    options: ['建设中国特色社会主义法治体系、建设社会主义法治国家', '只加强道德教育', '取消法律程序', '只靠行政命令'],
    answer: 0,
    explanation: '这是全面依法治国总目标的标准表述。',
    tags: ['法基'],
  },
  {
    id: 'pol-005',
    subject: '政治',
    prompt: '社会主义核心价值观中，个人层面的价值准则包括爱国、敬业、诚信和？',
    options: ['友善', '竞争', '速度', '服从'],
    answer: 0,
    explanation: '个人层面是爱国、敬业、诚信、友善。',
    tags: ['思修'],
  },
  {
    id: 'pol-006',
    subject: '政治',
    prompt: '矛盾问题的精髓是？',
    options: ['矛盾的普遍性和特殊性关系', '只看结果', '否认差异', '只看个别现象'],
    answer: 0,
    explanation: '矛盾普遍性和特殊性的关系是矛盾问题的精髓。',
    tags: ['马原'],
  },
  {
    id: 'math-001',
    subject: '高数（二）',
    prompt: '函数 y = 1 / (x - 2) 的定义域是？',
    options: ['x 不等于 2', '全体实数', 'x 等于 2', 'x 大于 2'],
    answer: 0,
    explanation: '分母不能为0，所以 x - 2 不等于0。',
    tags: ['函数'],
  },
  {
    id: 'math-002',
    subject: '高数（二）',
    prompt: 'lim(x->0) sin x / x 的值是？',
    options: ['1', '0', '无穷大', '-1'],
    answer: 0,
    explanation: '这是重要基本极限，值为1。',
    tags: ['极限'],
  },
  {
    id: 'math-003',
    subject: '高数（二）',
    prompt: '若 y = x^2，则 y 的导数是？',
    options: ['2x', 'x', 'x^3', '2'],
    answer: 0,
    explanation: '幂函数求导公式：(x^n)\' = n x^(n-1)。',
    tags: ['导数'],
  },
  {
    id: 'math-004',
    subject: '高数（二）',
    prompt: '不定积分 ∫ 1 dx 等于？',
    options: ['x + C', '1 + C', '0', 'x^2 + C'],
    answer: 0,
    explanation: '常数1的不定积分是 x + C。',
    tags: ['积分'],
  },
  {
    id: 'math-005',
    subject: '高数（二）',
    prompt: '两个互斥事件 A、B 的 P(A∪B) 等于？',
    options: ['P(A)+P(B)', 'P(A)P(B)', 'P(A)-P(B)', '1'],
    answer: 0,
    explanation: '互斥事件不能同时发生，并事件概率为概率之和。',
    tags: ['概率'],
  },
  {
    id: 'math-006',
    subject: '高数（二）',
    prompt: '若 f\'(x) > 0 在区间内恒成立，则 f(x) 在该区间？',
    options: ['单调递增', '单调递减', '恒为0', '没有定义'],
    answer: 0,
    explanation: '导数大于0表示函数在该区间单调递增。',
    tags: ['导数应用'],
  },
  {
    id: 'deg-001',
    subject: '学位与论文',
    prompt: '成人高等教育本科申请学士学位，通常最容易被忽视的长期风险是？',
    options: ['课程平均分和英语条件', '准考证颜色', '手机型号', '报名照片背景音乐'],
    answer: 0,
    explanation: '学位证不只看毕业，平均分、英语、论文和答辩都要满足学校规则。',
    tags: ['学位'],
  },
  {
    id: 'deg-002',
    subject: '学位与论文',
    prompt: '论文阶段最稳妥的做法是？',
    options: ['提前选资料充足的题目并预留查重修改时间', '截止当天才写', '只复制网上内容', '完全不看格式要求'],
    answer: 0,
    explanation: '论文要兼顾选题、资料、格式、查重和答辩，提前量越足越稳。',
    tags: ['论文'],
  },
  {
    id: 'adm-001',
    subject: '行政管理',
    prompt: '行政管理专业学习中，公共组织管理类题目最常见的答题方式是？',
    options: ['概念加原因加措施', '只写一个词', '只画图', '不写结论'],
    answer: 0,
    explanation: '管理类论述题通常要结构化展开：是什么、为什么、怎么办。',
    tags: ['专业课'],
  },
  {
    id: 'adm-002',
    subject: '行政管理',
    prompt: '入学后想稳妥毕业，哪项习惯最重要？',
    options: ['按平台要求完成学习、作业和期末复习', '只等最后一天', '不看通知', '只关注入学考试成绩'],
    answer: 0,
    explanation: '成考录取后仍需完成课程学习、作业、考试、论文等流程。',
    tags: ['毕业'],
  },
];
